openapi: 3.0.3
info:
  title: Geo Covid API
  version: 1.0.0
  description: Your project description
paths:
  /api-covid/groups/:
    get:
      operationId: api_covid_groups_list
      tags:
      - api-covid
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Report'
          description: ''
    post:
      operationId: api_covid_groups_create
      tags:
      - api-covid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Report'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Report'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Report'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Report'
          description: ''
  /api-covid/groups/{id}/:
    get:
      operationId: api_covid_groups_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this report.
        required: true
      tags:
      - api-covid
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Report'
          description: ''
    put:
      operationId: api_covid_groups_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this report.
        required: true
      tags:
      - api-covid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Report'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Report'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Report'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Report'
          description: ''
    patch:
      operationId: api_covid_groups_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this report.
        required: true
      tags:
      - api-covid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedReport'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedReport'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedReport'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Report'
          description: ''
    delete:
      operationId: api_covid_groups_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this report.
        required: true
      tags:
      - api-covid
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api-covid/users/:
    get:
      operationId: api_covid_users_list
      tags:
      - api-covid
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/State'
          description: ''
    post:
      operationId: api_covid_users_create
      tags:
      - api-covid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/State'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/State'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/State'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/State'
          description: ''
  /api-covid/users/{id}/:
    get:
      operationId: api_covid_users_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this state.
        required: true
      tags:
      - api-covid
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/State'
          description: ''
    put:
      operationId: api_covid_users_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this state.
        required: true
      tags:
      - api-covid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/State'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/State'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/State'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/State'
          description: ''
    patch:
      operationId: api_covid_users_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this state.
        required: true
      tags:
      - api-covid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedState'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedState'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedState'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/State'
          description: ''
    delete:
      operationId: api_covid_users_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this state.
        required: true
      tags:
      - api-covid
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
components:
  schemas:
    PatchedReport:
      type: object
      properties:
        date:
          type: string
          format: date-time
        state:
          type: string
          format: uri
        death:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
        positive:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
        negative:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
    PatchedState:
      type: object
      properties:
        name:
          type: string
        initials:
          type: string
          maxLength: 2
    Report:
      type: object
      properties:
        date:
          type: string
          format: date-time
        state:
          type: string
          format: uri
        death:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
        positive:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
        negative:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
      required:
      - date
      - state
    State:
      type: object
      properties:
        name:
          type: string
        initials:
          type: string
          maxLength: 2
      required:
      - initials
      - name
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
