# Generated by Django 4.0.6 on 2022-09-01 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initials', models.CharField(max_length=2, unique=True)),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('death', models.IntegerField(blank=True)),
                ('death_confirmed', models.IntegerField(blank=True)),
                ('death_increase', models.IntegerField(blank=True)),
                ('death_probable', models.IntegerField(blank=True)),
                ('hospitalized', models.IntegerField(blank=True)),
                ('hospitalized_cumulative', models.IntegerField(blank=True)),
                ('hospitalized_currently', models.IntegerField(blank=True)),
                ('hospitalized_increase', models.IntegerField(blank=True)),
                ('in_icu_cumulative', models.IntegerField(blank=True)),
                ('in_icu_currently', models.IntegerField(blank=True)),
                ('negative', models.IntegerField(blank=True)),
                ('negative_increase', models.IntegerField(blank=True)),
                ('negative_tests_antibody', models.IntegerField(blank=True)),
                ('negative_tests_people_antibody', models.IntegerField(blank=True)),
                ('negative_tests_viral', models.IntegerField(blank=True)),
                ('on_ventilator_cumulative', models.IntegerField(blank=True)),
                ('on_ventilator_currently', models.IntegerField(blank=True)),
                ('positive', models.IntegerField(blank=True)),
                ('positive_cases_viral', models.IntegerField(blank=True)),
                ('positive_increase', models.IntegerField(blank=True)),
                ('positive_score', models.IntegerField(blank=True)),
                ('positive_tests_antibody', models.IntegerField(blank=True)),
                ('positive_tests_antigen', models.IntegerField(blank=True)),
                ('positive_tests_people_antibody', models.IntegerField(blank=True)),
                ('positive_tests_people_antigen', models.IntegerField(blank=True)),
                ('positive_tests_viral', models.IntegerField(blank=True)),
                ('recovered', models.IntegerField(blank=True)),
                ('total_test_encounters_viral', models.IntegerField(blank=True)),
                ('total_test_encounters_viral_increase', models.IntegerField(blank=True)),
                ('total_test_results', models.IntegerField(blank=True)),
                ('total_test_results_increase', models.IntegerField(blank=True)),
                ('total_tests_antibody', models.IntegerField(blank=True)),
                ('total_tests_antigen', models.IntegerField(blank=True)),
                ('total_tests_people_antibody', models.IntegerField(blank=True)),
                ('total_tests_people_antigen', models.IntegerField(blank=True)),
                ('total_tests_people_viral', models.IntegerField(blank=True)),
                ('total_tests_people_viral_increase', models.IntegerField(blank=True)),
                ('total_tests_viral', models.IntegerField(blank=True)),
                ('total_tests_viral_increase', models.IntegerField(blank=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='us_covid_api.state')),
            ],
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['date'], name='us_covid_ap_date_07cecd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('date', 'state')},
        ),
    ]
