# Generated by Django 4.0.6 on 2022-09-01 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('us_covid_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['date']},
        ),
    ]
