from djongo import models

class State(models.Model):
    initials = models.CharField(max_length=2)
    name = models.TextField()
class Report(models.Model):
    date = models.DateTimeField(primary_key=True)
    state = models.ForeignKey(State, related_name='report', on_delete=models.CASCADE)

    # stats
    death = models.IntegerField()
    death_confirmed = models.IntegerField()
    death_increased = models.IntegerField()
    death_probable = models.IntegerField()
    hospitalized = models.IntegerField()
    hospitalized_cumulative = models.IntegerField()
    hospitalized_currently = models.IntegerField()
    hospitalized_increase = models.IntegerField()
    in_ICU_cumulative = models.IntegerField()
    in_ICU_currently = models.IntegerField()
    negative = models.IntegerField()
    negative_increase = models.IntegerField()
    negative_tests_antibody = models.IntegerField()
    negative_tests_people_antibody = models.IntegerField()
    negative_tests_viral = models.IntegerField()
    on_ventilation_cumulative = models.IntegerField()
    on_ventilation_currently = models.IntegerField()
    positive = models.IntegerField()
    positive_cases_viral = models.IntegerField()
    positive_increase = models.IntegerField()
    positive_score = models.IntegerField()
    positive_tests_antibody = models.IntegerField()
    positive_tests_antigen = models.IntegerField()
    positive_tests_people_antibody = models.IntegerField()
    positive_tests_people_antigen = models.IntegerField()
    positive_tests_viral = models.IntegerField()
    recovered = models.IntegerField()
    total_test_encounter_viral = models.IntegerField()
    total_test_encounter_viral_increase = models.IntegerField()
    total_test_result = models.IntegerField()
    total_test_result_increase = models.IntegerField()
    total_test_antibody = models.IntegerField()
    total_test_antigen = models.IntegerField()
    total_test_people_antibody = models.IntegerField()
    total_test_people_antigen = models.IntegerField()
    total_test_people_viral = models.IntegerField()
    total_test_people_viral_increase = models.IntegerField()
    total_test_viral = models.IntegerField()
    total_test_viral_increase = models.IntegerField()
